

SELECT CEDULA, SUM(CUMPLIMIENTO) AS total, AVG(CUMPLIMIENTO) AS promedio, MIN(CUMPLIMIENTO) AS minimo, MAX(CUMPLIMIENTO) AS maximo, COUNT(CUMPLIMIENTO) AS cantidad FROM `tbl_liquidacion` GROUP BY CEDULA
